In [35]:
# Loading packages
!pip install nltk

exec(open('utilities_cw.py').read())

# We fix the seeds to get consistent results
SEED = 1111
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
one.py is being run directly


In [36]:
from sklearn.model_selection import train_test_split

def augment_others(corpus, labels, n):  
    others = []
    for idx, label in enumerate(labels):
        if label == 2: 
            others.append(corpus[idx])
            
    for i in range(n):
        r = random.randint(0, len(others)) - 1      
        corpus.append(others[r])
        labels.append(2)

    return corpus, labels

train_file = 'offenseval-training-v1.tsv'
train_corpus, train_labels = parse_dataset_task_c(train_file)

print(len(train_corpus))
print(len(train_labels))

# inds = len([0 for l in train_labels if l == 0])
# groups = len([1 for l in train_labels if l == 1])
# oths = len([2 for l in train_labels if l == 2])

# print("Individual " + str(inds))
# print("Group " + str(groups))
# print("Others " + str(oths))

train_corpus, valid_corpus, train_labels, valid_labels = train_test_split(train_corpus, train_labels, test_size=0.25, random_state=42)

train_corpus, train_labels = augment_others(train_corpus, train_labels, 400)
valid_corpus, valid_labels = augment_others(valid_corpus, valid_labels, 100)
  
offensives = np.count_nonzero(train_labels)
nonoffensives = len(train_labels) - offensives

inds = len([0 for l in train_labels if l == 0])
groups = len([1 for l in train_labels if l == 1])
oths = len([2 for l in train_labels if l == 2])

print("Individual " + str(inds))
print("Group " + str(groups))
print("Others " + str(oths))
  
inds = len([0 for l in valid_labels if l == 0])
groups = len([1 for l in valid_labels if l == 1])
oths = len([2 for l in valid_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))  
  
print(train_corpus)
print(train_labels)

print(len(train_corpus))
print(len(train_labels))

3876
3876
Individual 1784
Group 824
Others 699
Individual 623
Offensives 250
Others 196
['user user user user user user user user user user so absurd  the left has been fielding violent feminists and communists in the form of antifa to attack the very peaceful transition of power for more than two years    i wonder if it will ever occur to you that you are the bad guys  i doubt you have the moral fortitude', 'user i am definitely for antifa members getting themselves killed', 'user user user user red roses swarm   conservatives pounce   we need our own verb', 'user fucking liar she was happy to play kate nash when you asked her', 'user i feel you dude it fucking sucks', 'user liar  set up by far left  liberals are so predictable  americans are into these empty stupid tactics  no one believes you  its a politically induced maneuver to attempt to delay the installation of a judge until after midterms  it wont work  no go write your book', 'user if anything wouldnt that be a state law  he

In [0]:
tokenize_f = tokenize_lemmatization

In [38]:
tokenized_corpus = tokenize_f(train_corpus)
print(len(tokenized_corpus))

3307


In [39]:
vocabulary = get_vocabulary(tokenized_corpus)
print(vocabulary)
print(len(vocabulary))

['user', 'absurd', '', 'left', 'fielding', 'violent', 'feminist', 'communist', 'form', 'antifa', 'attack', 'peaceful', 'transition', 'power', 'two', 'year', 'wonder', 'ever', 'occur', 'bad', 'guy', 'doubt', 'moral', 'fortitude', 'definitely', 'member', 'getting', 'killed', 'red', 'rose', 'swarm', 'conservative', 'pounce', 'need', 'verb', 'fucking', 'liar', 'happy', 'play', 'kate', 'nash', 'asked', 'feel', 'dude', 'suck', 'set', 'far', 'liberal', 'predictable', 'american', 'empty', 'stupid', 'tactic', 'one', 'belief', 'politically', 'induced', 'maneuver', 'attempt', 'delay', 'installation', 'judge', 'midterm', 'wont', 'work', 'go', 'write', 'book', 'anything', 'wouldnt', 'state', 'law', 'he', 'running', 'federal', 'office', 'think', 'texan', 'moronsabout', 'illegally', 'claiming', 'government', 'sending', 'summons', 'money', 'maga', 'start', 'kneeling', 'match', 'talk', 'oppressed', 'deep', 'america', 'b', 'nut', 'throwing', 'seeits', 'gun', 'control', 'leftist', 'dont', 'kill', 'people

In [40]:
word2idx = get_word2idx(tokenized_corpus, vocabulary)
print(len(word2idx))

7849


In [41]:
idx2word = get_idx2word(vocabulary)
print(len(idx2word))

7848


In [42]:
sentences_lengths = [len(sentence) for sentence in tokenized_corpus]
max_len = np.max(np.array(sentences_lengths))

train_sentences_tensor, train_labels_tensor = parse_input(tokenized_corpus, word2idx, train_labels, max_len)

print(train_sentences_tensor)
print(train_labels_tensor)

print(train_sentences_tensor.shape)
print(train_labels_tensor.shape)

tensor([[   1,    1,    1,  ...,    0,    0,    0],
        [   1,   25,   10,  ...,    0,    0,    0],
        [   1,    1,    1,  ...,    0,    0,    0],
        ...,
        [   1,   48,   77,  ...,    0,    0,    0],
        [   1,  160,  310,  ...,    0,    0,    0],
        [7126, 5819, 1976,  ...,    0,    0,    0]])
tensor([1., 1., 0.,  ..., 2., 2., 2.])
torch.Size([3307, 81])
torch.Size([3307])


In [43]:
test_file = 'validation.tsv'
test_corpus, test_labels = parse_dataset_task_c(test_file)

# TODO: maybe augment

inds = len([0 for l in test_labels if l == 0])
groups = len([1 for l in test_labels if l == 1])
oths = len([2 for l in test_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))
  
print(test_corpus)
print(test_labels)

print(len(test_corpus))
print(len(test_labels))

Individual 30
Offensives 4
Others 5
['hughhewitt mishacollins what the hell what does that tweet have to do with gun control maybe try to make your tweet have some sort of sense', 'guess ima have to beat some lil kids asses today cause lil becky not about to but my kid and get away with it ', 'breitbartnews little marco trump will get things done', 'realdonaldtrump everyone already know what you are trying to do with the fake news and witch hunt shit umits not working', 'if its not about me its about matt blah blah blah worrrry about your bf who makes you feel like shit but you act like yall good ', 'saeychung oh she is the worst ugh', 'breitbartnews obama fed the country shit sandwiches for 8 years maybe jim just has his addled mind confused about dates and who fed who what ', 'breitbartnews ironic because shes just like a shotguntwo cocks and shes ready to blow', 'hot usa latina girlfriend sucking so nicely 5 min ', 'realjack what you never see is us conservatives beating up on the m

In [0]:
def parse_in(tokenized_corpus, word2idx, labels, max_len):
    # we index our sentences
    vectorized_sentences = [[word2idx[token] for token in sentence if token in word2idx] for sentence in tokenized_corpus]
  
  
    # we create a tensor of a fixed size filled with zeroes for padding
    sentences_tensor = Variable(torch.zeros((len(vectorized_sentences), max_len))).long()
    sentences_lengths = [len(sentence) for sentence in vectorized_sentences]

    # we fill it with our vectorized sentences 
    for idx, (sentence, sentence_len) in enumerate(zip(vectorized_sentences, sentences_lengths)):
        sentences_tensor[idx, :sentence_len] = torch.LongTensor(sentence)
            
    labels_tensor = torch.FloatTensor(labels)

    return sentences_tensor, labels_tensor

In [45]:
tokenized_valid_corpus = tokenize_f(valid_corpus)

print(len(tokenized_valid_corpus))
print(len(valid_corpus))
print(len(valid_labels))

valid_sentences_tensor, valid_labels_tensor = parse_in(tokenized_valid_corpus, word2idx, valid_labels, max_len)

print(valid_sentences_tensor)
print(valid_labels_tensor)

print(max_len)

print(valid_sentences_tensor.shape)
print(valid_labels_tensor.shape)

1069
1069
1069
tensor([[   1,    1,   10,  ...,    0,    0,    0],
        [   1,    1,  803,  ...,    0,    0,    0],
        [   1,    1,  639,  ...,    0,    0,    0],
        ...,
        [ 559, 4112, 2466,  ...,    0,    0,    0],
        [   1,    1,  103,  ...,    0,    0,    0],
        [ 248,  249,  378,  ...,    0,    0,    0]])
tensor([0., 0., 0.,  ..., 2., 2., 2.])
81
torch.Size([1069, 81])
torch.Size([1069])


In [46]:
tokenized_test_corpus = tokenize_f(test_corpus)
test_sentences_tensor, test_labels_tensor = parse_input(tokenized_test_corpus, word2idx, test_labels, max_len)

print(test_sentences_tensor)
print(test_labels_tensor)

print(test_sentences_tensor.shape)
print(test_labels_tensor.shape)

tensor([[ 801, 1038,   98,  ...,    0,    0,    0],
        [ 543, 6948,  673,  ...,    0,    0,    0],
        [ 176,  340,  190,  ...,    0,    0,    0],
        ...,
        [ 198, 2494, 3799,  ...,    0,    0,    0],
        [ 345,    0,    0,  ...,    0,    0,    0],
        [1981,    3,  615,  ...,    0,    0,    0]])
tensor([0., 0., 0., 0., 0., 0., 1., 0., 2., 2., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 2., 0., 0., 1., 0., 0., 2., 0., 0., 0., 0.,
        0., 0., 2.])
torch.Size([39, 81])
torch.Size([39])


In [0]:
import torchvision

BATCH_SIZE = 1

def train_model_custom(model, optimizer, loss_fn, feature_train, target_train, feature_valid, target_valid, feature_test, target_test):
    
    training_set = torch.utils.data.TensorDataset(feature_train, target_train)
    train_input = torch.utils.data.DataLoader(training_set, batch_size=BATCH_SIZE,
                            shuffle=True)
    validation_set = torch.utils.data.TensorDataset(feature_valid, target_valid)
    valid_input = torch.utils.data.DataLoader(validation_set, batch_size=BATCH_SIZE,
                            shuffle=True)
    
    test_set = torch.utils.data.TensorDataset(feature_test, target_test)
    test_input = torch.utils.data.DataLoader(test_set, batch_size=BATCH_SIZE,
                            shuffle=True)

  
    for epoch in range(epochs):
        epoch_loss = 0
        epoch_predictions = []
        for batch, labels in train_input:
            labels = labels.type(torch.LongTensor)
            optimizer.zero_grad()
            model.hidden = model.init_hidden()

            predictions = model(batch)
#             print(predictions.view(1, -1))

            loss = loss_fn(predictions.view(1, -1), labels)
            epoch_loss += loss.item()
            loss.backward()
            optimizer.step()
        
            epoch_predictions.append(predictions.cpu().detach().numpy().tolist())
        
        
        model.eval()
        epoch_acc = accuracy_task_c(torch.tensor(epoch_predictions).view(-1, 3), target_train.type(torch.LongTensor))
  
        with torch.no_grad():
            valid_loss = 0
            predictions = []
            for batch, labels in valid_input:
                labels = labels.type(torch.LongTensor)
                predictions_valid = model(batch)
                loss = loss_fn(predictions_valid.view(1, -1), labels)
                valid_loss += loss.item()
                predictions.append(predictions_valid.cpu().numpy().tolist())
        
        valid_acc = accuracy_task_c(torch.tensor(predictions).view(-1, 3), target_valid.type(torch.LongTensor))

        print(f'| Epoch: {epoch:02} | Train Loss: {epoch_loss:.3f} | Train Acc: {epoch_acc*100:.2f}% | Val. Loss: {valid_loss:.3f} | Val. Acc: {valid_acc*100:.2f}% |')
    
    model.eval()

    with torch.no_grad():
        test_loss = 0
        predictions_test = []
        for batch, labels in test_input:
            labels = labels.type(torch.LongTensor)
            predictions = model(batch)
            loss = loss_fn(predictions.view(1, -1), labels)
            test_loss += loss.item()
            predictions_test.append(predictions.cpu().numpy().tolist())
        
        acc = accuracy_task_c(torch.tensor(predictions_test).view(-1, 3), target_test.type(torch.LongTensor))
        print(f'| Test Loss: {loss:.3f} | Test Acc: {acc*100:.2f}%')
        f_measure_task_c(torch.tensor(predictions_test).view(-1, 3), target_test.cpu().numpy())


In [0]:
class LSTM(nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, output_dim):
        super(LSTM, self).__init__()

        self.hidden_dim = hidden_dim
        self.word_embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.linear = nn.Linear(hidden_dim, output_dim)
        self.hidden = self.init_hidden()

    def init_hidden(self):
        # the axes semantics are (num_layers, minibatch_size, hidden_dim)
        return (torch.zeros(1, BATCH_SIZE, self.hidden_dim),
                torch.zeros(1, BATCH_SIZE, self.hidden_dim))

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        
        # if bidirectional num_directions = 2
        # input to lstm must have dims (seq_len, batch, input_size), (num_layers * num_directions, batch, hidden_size)
        seq_len = embeds.size(1)
        batch = embeds.size(0)
        input_size = embeds.size(2)
        lstm_out, self.hidden = self.lstm(embeds.permute(1, 0, 2), self.hidden)
        
        # keep only the last output of the sequence
        last = lstm_out.permute(1, 0, 2)[:, -1, :]
        res = self.linear(last)
        
        return res.squeeze()

In [52]:
epochs = 5

INPUT_DIM = len(word2idx)
EMBEDDING_DIM = 100
OUTPUT_DIM = 3
LEARNING_RATE = 0.0008

HIDDEN_DIM = 100

# model = LSTM(EMBEDDING_DIM, HIDDEN_DIM, INPUT_DIM, OUTPUT_DIM)
# model.hidden = model.init_hidden()

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
# loss_fn = nn.BCEWithLogitsLoss()
loss_fn = torch.nn.CrossEntropyLoss()

print(train_sentences_tensor.shape)
print(valid_sentences_tensor.shape)
print(test_sentences_tensor.shape)

train_model_custom(model, optimizer, loss_fn, train_sentences_tensor, train_labels_tensor, valid_sentences_tensor, valid_labels_tensor, test_sentences_tensor, test_labels_tensor)

torch.Size([3307, 81])
torch.Size([1069, 81])
torch.Size([39, 81])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:64: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


| Epoch: 00 | Train Loss: 1776.997 | Train Acc: 40.67% | Val. Loss: 1677.198 | Val. Acc: 29.65% |
| Epoch: 01 | Train Loss: 1498.239 | Train Acc: 40.82% | Val. Loss: 1800.279 | Val. Acc: 35.45% |
| Epoch: 02 | Train Loss: 1234.849 | Train Acc: 38.13% | Val. Loss: 2080.050 | Val. Acc: 40.97% |
| Epoch: 03 | Train Loss: 907.576 | Train Acc: 41.22% | Val. Loss: 2392.828 | Val. Acc: 36.48% |
| Epoch: 04 | Train Loss: 588.480 | Train Acc: 39.46% | Val. Loss: 2698.221 | Val. Acc: 24.13% |
| Test Loss: 3.443 | Test Acc: 10.26%
9
Test: Recall: 0.64, Precision: 0.23, F-measure: 0.34



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:76: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


In [0]:
testing = read_csv('test_set_taskc.tsv')

tweets = [row['tweet'] for row in testing]
tokenized_corpus = tokenize_f(tweets)

test_tensor, labels_tensor = parse_input(tokenized_corpus, word2idx, test_labels, max_len)

In [18]:
print(test_tensor)
print(test_tensor.shape)

predictions_test = []

for elem in test_tensor:
    prediction = model(elem.view(1, -1))
    predictions_test.append(prediction.cpu().detach().numpy().tolist())
print("DONE")
print(predictions_test)
predictions_test = torch.tensor(predictions_test)

output = torch.nn.functional.log_softmax(predictions_test).max(dim = 1)[1]

print(output)

print(len(output))

tensor([[ 371,  788,  223,  ...,    0,    0,    0],
        [2483, 4475, 2757,  ...,    0,    0,    0],
        [1857,   36,    0,  ...,    0,    0,    0],
        ...,
        [2566,  193,  116,  ...,    0,    0,    0],
        [  15, 5228,  116,  ...,    0,    0,    0],
        [ 109,  773, 6457,  ...,    0,    0,    0]])
torch.Size([213, 81])
DONE
[[-0.2867854833602905, 0.24012213945388794, 0.06823237240314484], [-0.28675705194473267, 0.2401149421930313, 0.06819616258144379], [-0.28673213720321655, 0.24009941518306732, 0.06820549070835114], [-0.11770470440387726, 0.17193126678466797, -0.03470148146152496], [-0.24569575488567352, 0.22355449199676514, 0.04319848120212555], [-0.28676116466522217, 0.2401099056005478, 0.06822894513607025], [0.8419718146324158, -0.21500162780284882, -0.6191657185554504], [1.5701993703842163, -0.5086258053779602, -1.0625855922698975], [2.011810302734375, -0.6866313815116882, -1.3315173387527466], [2.0131924152374268, -0.6871895790100098, -1.332354068756103

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  del sys.path[0]


In [0]:
ids = [row['id'] for row in testing]
out = []
for e in output.detach().numpy():
    if e == 0:
        out.append("IND")
    elif e == 1:
        out.append("GRP")
    else:
        out.append("OTH")
   
  
zipped = list(zip(ids, out))

with open('predictions_task_c_lstm_no_augment.csv', "w") as f:
    writer = csv.writer(f, dialect='excel')
    for row in zipped:
        writer.writerow(row)