In [17]:
# Loading packages
!pip install nltk

exec(open('utils.py').read())

# We fix the seeds to get consistent results
SEED = 1111
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
one.py is being run directly


In [2]:
from sklearn.model_selection import train_test_split

train_file = 'offenseval-training-v1.tsv'
train_corpus, train_labels_a, train_labels_b, train_labels_c = parse_dataset(train_file)

train_corpus, valid_corpus, train_labels_a, valid_labels_a = train_test_split(train_corpus, train_labels_a, test_size=0.15, random_state=42)

# train_corpus, train_labels_a = augment_negatives(train_corpus, train_labels_a)
  
offensives = np.count_nonzero(train_labels_a)
nonoffensives = len(train_labels_a) - offensives

print("Offensives " + str(offensives))
print("Non-offensives " + str(nonoffensives))
  
print(train_corpus)
print(train_labels_a)

print(len(train_corpus))
print(len(train_labels_a))

Offensives 3721
Non-offensives 7533
['user lmfaooooo foh w that free thought shit lmaoooo', 'user user lets see how many planes are turned around or crazy airport shut downs happen over next few days maybe a drinking game user  wwg1wga  maga', 'user user we dont support gun control in texas  so long beto', 'user he obviously doesnt care', 'user user user how is what she is doin g patriotic  i meanyoure basically saying it is a political act against the nominee likeshe waited to come forward until it would cause max damageim not saying shes lying at allbut what youre saying is crazy', 'user then resign you have done nothing to check el presidente you are part of the swamp and hold no nebraska values resign', 'user yes yes antifa is antifascist but celebrate openly when their political opponents are killed whatever you guys say', 'user user user as a kid of legal immigrants i can attest you are 100 correct they follow the law to the letter in most cases because they worked so damn hard t

In [3]:
tokenized_corpus = tokenize_stemming(train_corpus)
print(len(tokenized_corpus))

11254


In [4]:
vocabulary = get_vocabulary(tokenized_corpus)
print(vocabulary)
print(len(vocabulary))

['user', 'lmfaooooo', 'foh', 'w', 'free', 'thought', 'shit', 'lmaoooo', 'let', 'see', 'mani', 'plane', 'turn', 'around', 'crazi', 'airport', 'shut', 'down', 'happen', 'next', 'day', 'mayb', 'drink', 'game', '', 'wwg1wga', 'maga', 'dont', 'support', 'gun', 'control', 'texa', 'long', 'beto', 'obvious', 'doesnt', 'care', 'doin', 'g', 'patriot', 'meanyour', 'basic', 'say', 'polit', 'act', 'nomine', 'likesh', 'wait', 'come', 'forward', 'would', 'caus', 'max', 'damageim', 'she', 'lie', 'allbut', 'your', 'resign', 'done', 'noth', 'check', 'el', 'president', 'part', 'swamp', 'hold', 'nebraska', 'valu', 'ye', 'antifa', 'antifascist', 'celebr', 'openli', 'oppon', 'kill', 'whatev', 'guy', 'kid', 'legal', 'immigr', 'attest', '100', 'correct', 'follow', 'law', 'letter', 'case', 'work', 'damn', 'hard', 'get', 'wont', 'anyth', 'risk', 'statu', 'illeg', 'contempt', 'pull', 'scam', '247', 'know', 'make', 'professor', 'even', 'woker', 'he', 'nut', 'screw', 'keep', 'honestli', 'ode', 'that', 'exactli', '

In [5]:
word2idx = get_word2idx(tokenized_corpus, vocabulary)
print(len(word2idx))

14150


In [6]:
idx2word = get_idx2word(vocabulary)
print(len(idx2word))

14149


In [7]:
sentences_lengths = [len(sentence) for sentence in tokenized_corpus]
max_len = np.max(np.array(sentences_lengths))

train_sentences_tensor, train_labels_tensor = parse_input(tokenized_corpus, word2idx, train_labels_a, max_len)

print(train_sentences_tensor)
print(train_labels_tensor)

print(train_sentences_tensor.shape)
print(train_labels_tensor.shape)

tensor([[    1,     2,     3,  ...,     0,     0,     0],
        [    1,     1,     9,  ...,     0,     0,     0],
        [    1,     1,    28,  ...,     0,     0,     0],
        ...,
        [    1,     1,   694,  ...,     0,     0,     0],
        [    1,  7707,    45,  ...,     0,     0,     0],
        [    1,     1, 12999,  ...,     0,     0,     0]])
tensor([1., 0., 1.,  ..., 0., 0., 0.])
torch.Size([11254, 81])
torch.Size([11254])


In [8]:
test_file = 'validation.tsv'
test_corpus, test_labels_a, test_labels_b, test_labels_c = parse_dataset(test_file)

# TODO: maybe augment

offensives = np.count_nonzero(test_labels_a)
nonoffensives = len(test_labels_a) - offensives

print("Offensives " + str(offensives))
print("Non-offensives " + str(nonoffensives))

print(test_corpus)
print(test_labels_a)

print(len(test_corpus))
print(len(test_labels_a))

Offensives 77
Non-offensives 243
['breitbartnews ok shannon you tell the veterans in those locker rooms they have to stay there until the celebration of what they fought for is over', 'leftyglenn jaredeker bookuniverse hashtagzema ralphlombardi nathanhrubin fine because i could afford a gun if i wanted to i could fit it into my budget my budgeting is fine here in canada we have gun insurance and gun control and lotsa p', 'hot mom sucks off step son in shower 8 min httpstcoy0zi9f5z6j', 'bro these are some cute butt plugs im trying to cop httpstcorsnxrf4hti', 'arizona supreme court strikes down state legislation prohibiting medical marijuana use on public college c httpstcof2ptckxyvp', 'arguing gun control is wrong of me whoever has a strong opinion doesnt really care about facts they have a emotional connection to the issue and its a waste of me to argue when am i gonna learn that laughing out loud', 'doctors interest in medical marijuana far outpaces available research httpstcojldeuhdy

In [9]:
tokenized_valid_corpus = tokenize_stemming(valid_corpus)
valid_sentences_tensor, valid_labels_tensor = parse_input(tokenized_valid_corpus, word2idx, valid_labels_a, max_len)

print(valid_sentences_tensor)
print(valid_labels_tensor)

print(valid_sentences_tensor.shape)
print(valid_labels_tensor.shape)

tensor([[   1,    1, 1213,  ...,    0,    0,    0],
        [   1,    1,   30,  ...,    0,    0,    0],
        [   1, 5161, 1512,  ...,    0,    0,    0],
        ...,
        [   1,    1,    1,  ...,    0,    0,    0],
        [   1,  548,  450,  ...,    0,    0,    0],
        [   1,   71, 2204,  ...,    0,    0,    0]])
tensor([0., 0., 0.,  ..., 0., 1., 0.])
torch.Size([1986, 81])
torch.Size([1986])


In [10]:
tokenized_test_corpus = tokenize_stemming(test_corpus)
test_sentences_tensor, test_labels_tensor = parse_input(tokenized_test_corpus, word2idx, test_labels_a, max_len)

print(test_sentences_tensor)
print(test_labels_tensor)

print(test_sentences_tensor.shape)
print(test_labels_tensor.shape)

tensor([[ 642, 5391,  160,  ...,    0,    0,    0],
        [ 873,  294, 2429,  ...,    0,    0,    0],
        [2065, 4140, 2458,  ...,    0,    0,    0],
        ...,
        [  21, 3081,  719,  ...,    0,    0,    0],
        [1105,  372,  528,  ...,    0,    0,    0],
        [ 416,  356, 9680,  ...,    0,    0,    0]])
tensor([0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.

In [18]:
epochs=2

INPUT_DIM = len(word2idx)
EMBEDDING_DIM = 200
OUTPUT_DIM = 1
LEARNING_RATE = 0.0008

# the hyperparamerts specific to CNN
# we define the number of filters
N_OUT_CHANNELS = 100
# we define the window size
WINDOW_SIZE = 1
# we apply the dropout with the probability 0.5
DROPOUT = 0.5

# model = CNN(INPUT_DIM, EMBEDDING_DIM, N_OUT_CHANNELS, WINDOW_SIZE, OUTPUT_DIM, DROPOUT)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
loss_fn = nn.BCEWithLogitsLoss()

train_model(model, optimizer, loss_fn, train_sentences_tensor, train_labels_tensor, valid_sentences_tensor, valid_labels_tensor, test_sentences_tensor, test_labels_a)

| Epoch: 01 | Train Loss: 0.439 | Train Acc: 79.74% | Val. Loss: 0.513 | Val. Acc: 75.18% |
| Epoch: 02 | Train Loss: 0.437 | Train Acc: 80.18% | Val. Loss: 0.513 | Val. Acc: 75.23% |
Here
| Test Loss: 0.414 | Test Acc: 86.88%
49
Test: Recall: 0.64, Precision: 0.78, F-measure: 0.70

77
