In [4]:
# Loading packages
!pip install nltk

exec(open('utils.py').read())

# We fix the seeds to get consistent results
SEED = 1111
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
one.py is being run directly


In [0]:
def augment_untargeted(corpus, labels, n):
    untargeted = []
    for idx, label in enumerate(labels):
        if label == 0: 
            untargeted.append(corpus[idx])
       
    for i in range(n):
        r = random.randint(0, len(untargeted)) - 1      
        corpus.append(untargeted[r])
        labels.append(0)  
        
    return corpus, labels

In [6]:
from sklearn.model_selection import train_test_split

train_file = 'offenseval-training-v1.tsv'
train_corpus, train_labels = parse_dataset_task_c(train_file)

print(len(train_corpus))
print(len(train_labels))

train_corpus, valid_corpus, train_labels, valid_labels = train_test_split(train_corpus, train_labels, test_size=0.33, random_state=42)

# train_corpus, train_labels = augment_untargeted(train_corpus, train_labels, 1400)

# valid_corpus, valid_labels = augment_untargeted(valid_corpus, valid_labels, 800)

# train_corpus, train_labels_a = augment_negatives(train_corpus, train_labels_a)
  
offensives = np.count_nonzero(train_labels)
nonoffensives = len(train_labels) - offensives

print("Offensives " + str(offensives))
print("Non-offensives " + str(nonoffensives))
  
print(train_corpus)
print(train_labels)

print(len(train_corpus))
print(len(train_labels))

3876
3876
Offensives 996
Non-offensives 1600
[' reans arcane gale is broken if he is gonna be able to use that from scratch in sen iv  because of his demon form its gonna be cool  using it in every battle', 'user deep corruption in the puerto rican government is the cause for the ppls misery billions sent amp you dont have the foresight to harden amp secure the power system on an island that will most likely get hit again this is the puerto ricans government ms fault', 'user user user i didnt see the referred to tv segment and i dont support the response but it is very easy to see how you as a race baiter can bring out the emotions you are trying to elicit it is unfortunate that ur willing to sacrifice black people to make you such a big man', 'user fool on the hill ', 'user user its easier for pod to believe both sides are terrible then he doesnt have to honestly look at the conservatives', 'user the war on conservatives antifa', 'user damn hope you find some bitch  i bought some yest

In [0]:
tokenized_corpus = tokenize(train_corpus)
print(len(tokenized_corpus))

2596


In [0]:
vocabulary = get_vocabulary(tokenized_corpus)
print(vocabulary)
print(len(vocabulary))

['', 'reans', 'arcane', 'gale', 'is', 'broken', 'if', 'he', 'gonna', 'be', 'able', 'to', 'use', 'that', 'from', 'scratch', 'in', 'sen', 'iv', 'because', 'of', 'his', 'demon', 'form', 'its', 'cool', 'using', 'it', 'every', 'battle', 'user', 'deep', 'corruption', 'the', 'puerto', 'rican', 'government', 'cause', 'for', 'ppls', 'misery', 'billions', 'sent', 'amp', 'you', 'dont', 'have', 'foresight', 'harden', 'secure', 'power', 'system', 'on', 'an', 'island', 'will', 'most', 'likely', 'get', 'hit', 'again', 'this', 'ricans', 'ms', 'fault', 'i', 'didnt', 'see', 'referred', 'tv', 'segment', 'and', 'support', 'response', 'but', 'very', 'easy', 'how', 'as', 'a', 'race', 'baiter', 'can', 'bring', 'out', 'emotions', 'are', 'trying', 'elicit', 'unfortunate', 'ur', 'willing', 'sacrifice', 'black', 'people', 'make', 'such', 'big', 'man', 'fool', 'hill', 'easier', 'pod', 'believe', 'both', 'sides', 'terrible', 'then', 'doesnt', 'honestly', 'look', 'at', 'conservatives', 'war', 'antifa', 'damn', 'hop

In [0]:
word2idx = get_word2idx(tokenized_corpus, vocabulary)
print(len(word2idx))

8099


In [0]:
idx2word = get_idx2word(vocabulary)
print(len(idx2word))

8098


In [0]:
sentences_lengths = [len(sentence) for sentence in tokenized_corpus]
max_len = np.max(np.array(sentences_lengths))

train_sentences_tensor, train_labels_tensor = parse_input(tokenized_corpus, word2idx, train_labels, max_len)

print(train_sentences_tensor)
print(train_labels_tensor)

print(train_sentences_tensor.shape)
print(train_labels_tensor.shape)

tensor([[   1,    2,    3,  ...,    0,    0,    0],
        [  31,   32,   33,  ...,    0,    0,    0],
        [  31,   31,   31,  ...,    0,    0,    0],
        ...,
        [  31,  127,  149,  ...,    0,    0,    0],
        [  31,  331, 1896,  ...,    0,    0,    0],
        [  31,  120,  414,  ...,    0,    0,    0]])
tensor([0., 0., 0.,  ..., 1., 1., 1.])
torch.Size([2596, 102])
torch.Size([2596])


In [0]:
test_file = 'validation.tsv'
test_corpus, test_labels = parse_dataset_t_b(test_file)

# TODO: maybe augment

offensives = np.count_nonzero(test_labels)
nonoffensives = len(test_labels) - offensives

print("Offensives " + str(offensives))
print("Non-offensives " + str(nonoffensives))

print(test_corpus)
print(test_labels)

print(len(test_corpus))
print(len(test_labels))

Offensives 38
Non-offensives 39
['hot mom sucks off step son in shower 8 min httpstcoy0zi9f5z6j', 'bro these are some cute butt plugs im trying to cop httpstcorsnxrf4hti', 'jo2timess now thats the dumbest shit i have ever heard in my lifelike wtf', 'agreed when all of this drama was unfolding agents i know said comey had stacks of resignation letters piling up on his desk amp no one wanted to interact with him anymore when he let clinton off the hook there were agents throwing shit at their tvs you are a disgrace comey httpstcorzfblgewby', 'cattunneycbc pdmcleod yeah anyone who says that is a directive is full of shit', 'hughhewitt mishacollins what the hell what does that tweet have to do with gun control maybe try to make your tweet have some sort of sense', 'and not give a single fuck httpstcob6vchavyzl', 'guess ima have to beat some lil kids asses today cause lil becky not about to but my kid and get away with it httpstcorprmn2tban', 'im freeeee worst experience of my fucking life'

In [0]:
def parse_in(tokenized_corpus, word2idx, labels, max_len):
    # we index our sentences
    vectorized_sentences = [[word2idx[token] for token in sentence if token in word2idx] for sentence in tokenized_corpus]
  
  
    # we create a tensor of a fixed size filled with zeroes for padding
    sentences_tensor = Variable(torch.zeros((len(vectorized_sentences), max_len))).long()
    sentences_lengths = [len(sentence) for sentence in vectorized_sentences]

    # we fill it with our vectorized sentences 
    for idx, (sentence, sentence_len) in enumerate(zip(vectorized_sentences, sentences_lengths)):
        try:
            sentences_tensor[idx, :sentence_len] = torch.LongTensor(sentence)
        except:
            print(idx)
            print(sentence_len)
            print(sentence)
            print(len(sentence))
            break
            
    labels_tensor = torch.FloatTensor(labels)

    return sentences_tensor, labels_tensor

In [0]:
tokenized_valid_corpus = tokenize(valid_corpus)

print(len(tokenized_valid_corpus))
print(len(valid_corpus))
print(len(valid_labels))

valid_sentences_tensor, valid_labels_tensor = parse_in(tokenized_valid_corpus, word2idx, valid_labels, max_len)

print(valid_sentences_tensor)
print(valid_labels_tensor)

print(max_len)

print("Aici " + str(valid_sentences_tensor[958]))

print(valid_sentences_tensor.shape)
print(valid_labels_tensor.shape)

1280
1280
1280
tensor([[  31,   31,  112,  ...,    0,    0,    0],
        [  31,   31, 1200,  ...,    0,    0,    0],
        [  31,   31,  328,  ...,    0,    0,    0],
        ...,
        [  31, 1803,    1,  ...,    0,    0,    0],
        [  31,   31,   31,  ...,    0,    0,    0],
        [  31,   66, 1402,  ...,    0,    0,    0]])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
102
Aici tensor([  31,  586,   12,  215,   47,  119,  979,  327, 1341,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,  

In [0]:
tokenized_test_corpus = tokenize(test_corpus)
test_sentences_tensor, test_labels_tensor = parse_input(tokenized_test_corpus, word2idx, test_labels, max_len)

print(test_sentences_tensor)
print(test_labels_tensor)

print(test_sentences_tensor.shape)
print(test_labels_tensor.shape)

tensor([[ 865, 3927,  172,  ...,    0,    0,    0],
        [ 858,  453,   87,  ...,    0,    0,    0],
        [ 156,  458,   34,  ...,    0,    0,    0],
        ...,
        [ 358,    0,    0,  ...,    0,    0,    0],
        [ 248,    1,   45,  ...,    0,    0,    0],
        [3148,  128,  127,  ...,    0,    0,    0]])
tensor([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
        0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 1., 1., 0.])
torch.Size([77, 102])
torch.Size([77])


In [0]:
def train_model_custom(model, optimizer, loss_fn, feature_train, target_train, feature_valid, target_valid, feature_test, target_test):
#     target_train = target_train.type(torch.LongTensor)
#     target_valid = target_valid.type(torch.LongTensor)
    for epoch in range(1, epochs+1):
        model.train()
        optimizer.zero_grad()
        predictions = model(feature_train)
#         print(predictions)
#         print(predictions.shape)
#         print(target_train)
#         print(target_train.shape)
        loss = loss_fn(predictions, target_train.type(torch.LongTensor))
        acc = accuracy(predictions, target_train.type(torch.LongTensor))
        loss.backward()
        optimizer.step()

        epoch_loss = loss.item()
        epoch_acc = acc
  
        model.eval()
  
        with torch.no_grad():

            predictions_valid = model(feature_valid)
            loss = loss_fn(predictions_valid, target_valid.type(torch.LongTensor))
            acc = accuracy(predictions_valid, target_valid.type(torch.LongTensor))
            valid_loss = loss.item()
            valid_acc = acc

        print(f'| Epoch: {epoch:02} | Train Loss: {epoch_loss:.3f} | Train Acc: {epoch_acc*100:.2f}% | Val. Loss: {valid_loss:.3f} | Val. Acc: {valid_acc*100:.2f}% |')
    
    model.eval()

    with torch.no_grad():
 
        predictions = model(feature_test)
        loss = loss_fn(predictions, torch.tensor(target_test).type(torch.LongTensor))
        acc = accuracy(predictions, torch.tensor(target_test).type(torch.LongTensor))
        print(f'| Test Loss: {loss:.3f} | Test Acc: {acc*100:.2f}%')
        f_measure(predictions, target_test)

    print(np.count_nonzero(target_test))

In [0]:
epochs=40

INPUT_DIM = len(word2idx)
EMBEDDING_DIM = 100
OUTPUT_DIM = 3
LEARNING_RATE = 0.0008

# the hyperparamerts specific to CNN
# we define the number of filters
N_OUT_CHANNELS = 100
# we define the window size
WINDOW_SIZE = 1
# we apply the dropout with the probability 0.5
DROPOUT = 0.5

model = CNN(INPUT_DIM, EMBEDDING_DIM, N_OUT_CHANNELS, WINDOW_SIZE, OUTPUT_DIM, DROPOUT)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
# loss_fn = nn.BCEWithLogitsLoss()
loss_fn = torch.nn.CrossEntropyLoss()

train_model_custom(model, optimizer, loss_fn, train_sentences_tensor, train_labels_tensor, valid_sentences_tensor, valid_labels_tensor, test_sentences_tensor, test_labels)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:65: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


| Epoch: 01 | Train Loss: 1.127 | Train Acc: 40.14% | Val. Loss: 0.972 | Val. Acc: 60.86% |
| Epoch: 02 | Train Loss: 1.061 | Train Acc: 45.26% | Val. Loss: 0.929 | Val. Acc: 62.66% |
| Epoch: 03 | Train Loss: 1.040 | Train Acc: 50.81% | Val. Loss: 0.903 | Val. Acc: 63.05% |
| Epoch: 04 | Train Loss: 1.002 | Train Acc: 54.62% | Val. Loss: 0.889 | Val. Acc: 63.05% |
| Epoch: 05 | Train Loss: 0.970 | Train Acc: 58.05% | Val. Loss: 0.882 | Val. Acc: 63.05% |
| Epoch: 06 | Train Loss: 0.958 | Train Acc: 58.98% | Val. Loss: 0.880 | Val. Acc: 63.05% |
| Epoch: 07 | Train Loss: 0.960 | Train Acc: 58.82% | Val. Loss: 0.878 | Val. Acc: 63.05% |
| Epoch: 08 | Train Loss: 0.937 | Train Acc: 59.71% | Val. Loss: 0.877 | Val. Acc: 63.05% |
| Epoch: 09 | Train Loss: 0.966 | Train Acc: 58.98% | Val. Loss: 0.876 | Val. Acc: 63.05% |
| Epoch: 10 | Train Loss: 0.941 | Train Acc: 59.67% | Val. Loss: 0.874 | Val. Acc: 63.05% |
| Epoch: 11 | Train Loss: 0.921 | Train Acc: 60.44% | Val. Loss: 0.873 | Val. Ac

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:72: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
