In [127]:
# Loading packages
!pip install nltk

exec(open('utilities_cw.py').read())

# We fix the seeds to get consistent results
SEED = 1111
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
one.py is being run directly


In [128]:
from sklearn.model_selection import train_test_split

def augment_others(corpus, labels, n):  
    others = []
    for idx, label in enumerate(labels):
        if label == 2: 
            others.append(corpus[idx])
            
    for i in range(n):
        r = random.randint(0, len(others)) - 1      
        corpus.append(others[r])
        labels.append(2)

    return corpus, labels

train_file = 'offenseval-training-v1.tsv'
train_corpus, train_labels = parse_dataset_task_c(train_file)

print(len(train_corpus))
print(len(train_labels))

train_corpus, valid_corpus, train_labels, valid_labels = train_test_split(train_corpus, train_labels, test_size=0.2, random_state=42)

train_corpus, train_labels = augment_others(train_corpus, train_labels, 400)
valid_corpus, valid_labels = augment_others(valid_corpus, valid_labels, 100)
  
offensives = np.count_nonzero(train_labels)
nonoffensives = len(train_labels) - offensives

inds = len([0 for l in train_labels if l == 0])
groups = len([1 for l in train_labels if l == 1])
oths = len([2 for l in train_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))
  
inds = len([0 for l in valid_labels if l == 0])
groups = len([1 for l in valid_labels if l == 1])
oths = len([2 for l in valid_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))  
  
print(train_corpus)
print(train_labels)

print(len(train_corpus))
print(len(train_labels))

3876
3876
Individual 1906
Offensives 872
Others 722
Individual 501
Offensives 202
Others 173
['user go away my child you are so boring that you cant even entertain a doubt', 'user i think i liked it better when conservatives pretended that rape is bad now they are claiming rape gets better with time', 'pigeon girl can also send pigeons to poop on all maga hats', 'user fuckkk  i know i seen bitch thats a slapper laugh my a.. off', 'user i want to fight one of you for real you are taking the piss url', 'user user not supporting trump is the lowest low bar im glad someone doesnt support trump it doesnt make them an ally there are plenty of conservatives who hate trump who arent also pure trash', 'aint it fun when a manager has a stick up his ass that would make a redwood selfconscious about its size', 'user he should be given 5000 volts', 'user bono can go away now the 90s are over you sick now', 'user user user user you are a liberal who doesnt even live in fl', 'user user user user who 

In [0]:
tokenize_f = tokenize_stemming

In [130]:
tokenized_corpus = tokenize_f(train_corpus)
print(len(tokenized_corpus))

3500


In [131]:
vocabulary = get_vocabulary(tokenized_corpus)
print(vocabulary)
print(len(vocabulary))

['user', 'go', 'away', 'child', 'bore', 'cant', 'even', 'entertain', 'doubt', 'think', 'like', 'better', 'conserv', 'pretend', 'rape', 'bad', 'claim', 'get', 'time', 'pigeon', 'girl', 'also', 'send', 'poop', 'maga', 'hat', 'fuckkk', '', 'know', 'seen', 'bitch', 'that', 'slapper', 'laugh', 'a..', 'want', 'fight', 'one', 'real', 'take', 'piss', 'url', 'support', 'trump', 'lowest', 'low', 'bar', 'im', 'glad', 'someon', 'doesnt', 'make', 'alli', 'plenti', 'hate', 'arent', 'pure', 'trash', 'aint', 'fun', 'manag', 'stick', 'ass', 'would', 'redwood', 'selfconsci', 'size', 'given', '5000', 'volt', 'bono', '90', 'sick', 'liber', 'live', 'fl', 'lose', 'entir', 'thing', 'block', 'kavanaugh', 'lean', 'bit', 'side', 'nomin', 'play', 'game', 'see', 'youv', 'brainwash', 'mainstream', 'media', 'dont', 'messag', 'man', 'woulda', 'start', 'hit', 'wall', 'shit', 'noth', 'dri', 'wood', 'beam', 'door', 'dumb', 'forgiv', 'manner', 'pile', 'shiit', 'said', 'give', 'cancer', 'ltgod', 'chosen', 'leader', 'fuck

In [132]:
word2idx = get_word2idx(tokenized_corpus, vocabulary)
print(len(word2idx))

6809


In [133]:
idx2word = get_idx2word(vocabulary)
print(len(idx2word))

6808


In [134]:
sentences_lengths = [len(sentence) for sentence in tokenized_corpus]
max_len = np.max(np.array(sentences_lengths))

train_sentences_tensor, train_labels_tensor = parse_input(tokenized_corpus, word2idx, train_labels, max_len)

print(train_sentences_tensor)
print(train_labels_tensor)

print(train_sentences_tensor.shape)
print(train_labels_tensor.shape)

tensor([[   1,    2,    3,  ...,    0,    0,    0],
        [   1,   10,   11,  ...,    0,    0,    0],
        [  20,   21,   22,  ...,    0,    0,    0],
        ...,
        [4344,    1,    1,  ...,    0,    0,    0],
        [   1, 3383,  229,  ...,    0,    0,    0],
        [   1, 4188, 2055,  ...,    0,    0,    0]])
tensor([0., 1., 0.,  ..., 2., 2., 2.])
torch.Size([3500, 81])
torch.Size([3500])


In [135]:
test_file = 'validation.tsv'
test_corpus, test_labels = parse_dataset_task_c(test_file)

# TODO: maybe augment

inds = len([0 for l in test_labels if l == 0])
groups = len([1 for l in test_labels if l == 1])
oths = len([2 for l in test_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))
  
print(test_corpus)
print(test_labels)

print(len(test_corpus))
print(len(test_labels))

Individual 30
Offensives 4
Others 5
['hughhewitt mishacollins what the hell what does that tweet have to do with gun control maybe try to make your tweet have some sort of sense', 'guess ima have to beat some lil kids asses today cause lil becky not about to but my kid and get away with it ', 'breitbartnews little marco trump will get things done', 'realdonaldtrump everyone already know what you are trying to do with the fake news and witch hunt shit umits not working', 'if its not about me its about matt blah blah blah worrrry about your bf who makes you feel like shit but you act like yall good ', 'saeychung oh she is the worst ugh', 'breitbartnews obama fed the country shit sandwiches for 8 years maybe jim just has his addled mind confused about dates and who fed who what ', 'breitbartnews ironic because shes just like a shotguntwo cocks and shes ready to blow', 'hot usa latina girlfriend sucking so nicely 5 min ', 'realjack what you never see is us conservatives beating up on the m

In [0]:
def parse_in(tokenized_corpus, word2idx, labels, max_len):
    # we index our sentences
    vectorized_sentences = [[word2idx[token] for token in sentence if token in word2idx] for sentence in tokenized_corpus]
  
  
    # we create a tensor of a fixed size filled with zeroes for padding
    sentences_tensor = Variable(torch.zeros((len(vectorized_sentences), max_len))).long()
    sentences_lengths = [len(sentence) for sentence in vectorized_sentences]

    # we fill it with our vectorized sentences 
    for idx, (sentence, sentence_len) in enumerate(zip(vectorized_sentences, sentences_lengths)):
        sentences_tensor[idx, :sentence_len] = torch.LongTensor(sentence)
            
    labels_tensor = torch.FloatTensor(labels)

    return sentences_tensor, labels_tensor

In [137]:
tokenized_valid_corpus = tokenize_f(valid_corpus)

print(len(tokenized_valid_corpus))
print(len(valid_corpus))
print(len(valid_labels))

valid_sentences_tensor, valid_labels_tensor = parse_in(tokenized_valid_corpus, word2idx, valid_labels, max_len)

print(valid_sentences_tensor)
print(valid_labels_tensor)

print(max_len)

print(valid_sentences_tensor.shape)
print(valid_labels_tensor.shape)

876
876
876
tensor([[   1,    1,  229,  ...,    0,    0,    0],
        [   1,    1, 1539,  ...,    0,    0,    0],
        [   1,    1,   34,  ...,    0,    0,    0],
        ...,
        [   1,  174,  234,  ...,    0,    0,    0],
        [   1,  111, 1512,  ...,    0,    0,    0],
        [   1,   40, 1966,  ...,    0,    0,    0]])
tensor([0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 2., 1., 0., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 2., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 2., 0.,
        1., 2., 0., 1., 0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 2., 1., 1.,
        2., 2., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 2., 0., 1., 0., 2., 2., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 2., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 1.

In [138]:
tokenized_test_corpus = tokenize_f(test_corpus)
test_sentences_tensor, test_labels_tensor = parse_input(tokenized_test_corpus, word2idx, test_labels, max_len)

print(test_sentences_tensor)
print(test_labels_tensor)

print(test_sentences_tensor.shape)
print(test_labels_tensor.shape)

tensor([[1538,  270,  161,  ...,    0,    0,    0],
        [ 760, 6118,  281,  ...,    0,    0,    0],
        [1114,   44,   18,  ...,    0,    0,    0],
        ...,
        [1201,  724, 3688,  ...,    0,    0,    0],
        [ 117,    0,    0,  ...,    0,    0,    0],
        [ 381,   28,  478,  ...,    0,    0,    0]])
tensor([0., 0., 0., 0., 0., 0., 1., 0., 2., 2., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 2., 0., 0., 1., 0., 0., 2., 0., 0., 0., 0.,
        0., 0., 2.])
torch.Size([39, 81])
torch.Size([39])


In [0]:
def train_model_custom(model, optimizer, loss_fn, feature_train, target_train, feature_valid, target_valid, feature_test, target_test):
#     target_train = target_train.type(torch.LongTensor)
#     target_valid = target_valid.type(torch.LongTensor)
    for epoch in range(1, epochs+1):
        model.train()
        optimizer.zero_grad()
        predictions = model(feature_train)
#         print(predictions)
#         print(predictions.shape)
#         print(target_train)
#         print(target_train.shape)
        loss = loss_fn(predictions, target_train.type(torch.LongTensor))
        acc = accuracy_task_c(predictions, target_train.type(torch.LongTensor))
        loss.backward()
        optimizer.step()

        epoch_loss = loss.item()
        epoch_acc = acc
  
        model.eval()
  
        with torch.no_grad():

            predictions_valid = model(feature_valid)
            loss = loss_fn(predictions_valid, target_valid.type(torch.LongTensor))
            acc = accuracy_task_c(predictions_valid, target_valid.type(torch.LongTensor))
            valid_loss = loss.item()
            valid_acc = acc

        print(f'| Epoch: {epoch:02} | Train Loss: {epoch_loss:.3f} | Train Acc: {epoch_acc*100:.2f}% | Val. Loss: {valid_loss:.3f} | Val. Acc: {valid_acc*100:.2f}% |')
    
    model.eval()

    with torch.no_grad():
 
        predictions = model(feature_test)
        loss = loss_fn(predictions, torch.tensor(target_test).type(torch.LongTensor))
        acc = accuracy_task_c(predictions, torch.tensor(target_test).type(torch.LongTensor))
        print(f'| Test Loss: {loss:.3f} | Test Acc: {acc*100:.2f}%')
        f_measure_task_c(predictions, target_test)

    print(np.count_nonzero(target_test))

In [140]:
epochs=100

INPUT_DIM = len(word2idx)
EMBEDDING_DIM = 100
OUTPUT_DIM = 3
LEARNING_RATE = 0.0008

# the hyperparamerts specific to CNN
# we define the number of filters
N_OUT_CHANNELS = 100
# we define the window size
WINDOW_SIZE = 1
# we apply the dropout with the probability 0.5
DROPOUT = 0.5

model = CNN(INPUT_DIM, EMBEDDING_DIM, N_OUT_CHANNELS, WINDOW_SIZE, OUTPUT_DIM, DROPOUT)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
# loss_fn = nn.BCEWithLogitsLoss()
loss_fn = torch.nn.CrossEntropyLoss()

train_model_custom(model, optimizer, loss_fn, train_sentences_tensor, train_labels_tensor, valid_sentences_tensor, valid_labels_tensor, test_sentences_tensor, test_labels)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:64: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


| Epoch: 01 | Train Loss: 1.227 | Train Acc: 35.54% | Val. Loss: 1.059 | Val. Acc: 46.92% |
| Epoch: 02 | Train Loss: 1.179 | Train Acc: 39.71% | Val. Loss: 1.014 | Val. Acc: 54.00% |
| Epoch: 03 | Train Loss: 1.131 | Train Acc: 43.54% | Val. Loss: 0.984 | Val. Acc: 56.62% |
| Epoch: 04 | Train Loss: 1.110 | Train Acc: 46.54% | Val. Loss: 0.968 | Val. Acc: 56.85% |
| Epoch: 05 | Train Loss: 1.081 | Train Acc: 49.31% | Val. Loss: 0.961 | Val. Acc: 56.96% |
| Epoch: 06 | Train Loss: 1.070 | Train Acc: 50.00% | Val. Loss: 0.960 | Val. Acc: 56.96% |
| Epoch: 07 | Train Loss: 1.087 | Train Acc: 49.66% | Val. Loss: 0.962 | Val. Acc: 57.08% |
| Epoch: 08 | Train Loss: 1.061 | Train Acc: 52.20% | Val. Loss: 0.963 | Val. Acc: 56.96% |
| Epoch: 09 | Train Loss: 1.069 | Train Acc: 51.69% | Val. Loss: 0.964 | Val. Acc: 56.96% |
| Epoch: 10 | Train Loss: 1.056 | Train Acc: 51.71% | Val. Loss: 0.963 | Val. Acc: 56.85% |
| Epoch: 11 | Train Loss: 1.058 | Train Acc: 51.31% | Val. Loss: 0.961 | Val. Ac

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:76: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


In [0]:
testing = read_csv('test_set_taskc.tsv')

tweets = [row['tweet'] for row in testing]
tokenized_corpus = tokenize_f(tweets)

test_tensor, labels_tensor = parse_input(tokenized_corpus, word2idx, test_labels, max_len)

In [142]:
predictions_test = model(test_tensor).squeeze(1)

output = torch.nn.functional.log_softmax(predictions_test).max(dim = 1)[1]

print(output)

print(len(output))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])
213


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
ids = [row['id'] for row in testing]
out = []
for e in output.detach().numpy():
    if e == 0:
        out.append("IND")
    elif e == 1:
        out.append("GRP")
    else:
        out.append("OTH")
   
  
zipped = list(zip(ids, out))

with open('predictions_task_c_split_stemming_augment.csv', "w") as f:
    writer = csv.writer(f, dialect='excel')
    for row in zipped:
        writer.writerow(row)