In [31]:
# Loading packages
!pip install nltk

exec(open('utilities_cw.py').read())

# We fix the seeds to get consistent results
SEED = 1111
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
one.py is being run directly


In [32]:
from sklearn.model_selection import train_test_split

train_file = 'offenseval-training-v1.tsv'
train_corpus, train_labels = parse_dataset_task_c(train_file)

print(len(train_corpus))
print(len(train_labels))

3876
3876


In [0]:
def augment_others(corpus, labels, n):  
    others = []
    for idx, label in enumerate(labels):
        if label == 2: 
            others.append(corpus[idx])
            
    for i in range(n):
        r = random.randint(0, len(others)) - 1      
        corpus.append(others[r])
        labels.append(2)

    return corpus, labels

In [35]:
train_corpus, valid_corpus, train_labels, valid_labels = train_test_split(train_corpus, train_labels, test_size=0.25, random_state=42)

train_corpus, train_labels = augment_others(train_corpus, train_labels, 300)
valid_corpus, valid_labels = augment_others(valid_corpus, valid_labels, 70)
  
inds = len([0 for l in train_labels if l == 0])
groups = len([1 for l in train_labels if l == 1])
oths = len([2 for l in train_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))
  
inds = len([0 for l in valid_labels if l == 0])
groups = len([1 for l in valid_labels if l == 1])
oths = len([2 for l in valid_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))  
  
print(train_corpus)
print(train_labels)

print(len(train_corpus))
print(len(train_labels))

Individual 1339
Offensives 608
Others 533
Individual 445
Offensives 216
Others 136
['user user user how convenient a conservative dummy believes people are selectively unemployedconservatives always try to use this type of propaganda no factsjust their warped conservative beliefs its very clearmany conservatives like user dont have the ability to learn or think', 'user and dying a slow death such a shame', 'user also shes thick as shit despite her posh brainy voice on qt when the refugee crisis was at its peakshe said they should come in because there may be surgeons amp dentists amongst themfecking leftie lunaticscruffbag', 'user you are an asshole', 'redwave a coming thats ok tho no conservative will harm you bc of your political ideals  cant say the same for liberals tho liberals can be vile and nasty to opposing views url', 'it will be hard to believe any female accusersever againespecially liberals who lie for personal and political gain url', 'user user user most stupid tweet yet

In [0]:
tokenize_f = tokenize_stemming

In [37]:
tokenized_corpus = tokenize_f(train_corpus)
print(len(tokenized_corpus))

2480


In [38]:
vocabulary = get_vocabulary(tokenized_corpus)
print(vocabulary)
print(len(vocabulary))

['user', 'conveni', 'conserv', 'dummi', 'believ', 'peopl', 'select', 'unemployedconserv', 'alway', 'tri', 'use', 'type', 'propaganda', 'factsjust', 'warp', 'belief', 'clearmani', 'like', 'dont', 'abil', 'learn', 'think', 'die', 'slow', 'death', 'shame', 'also', 'she', 'thick', 'shit', 'despit', 'posh', 'braini', 'voic', 'qt', 'refuge', 'crisi', 'peaksh', 'said', 'come', 'may', 'surgeon', 'amp', 'dentist', 'amongst', 'themfeck', 'lefti', 'lunaticscruffbag', 'asshol', 'redwav', 'that', 'ok', 'tho', 'harm', 'bc', 'polit', 'ideal', '', 'cant', 'say', 'liber', 'vile', 'nasti', 'oppos', 'view', 'url', 'hard', 'femal', 'accusersev', 'againespeci', 'lie', 'person', 'gain', 'stupid', 'tweet', 'yetand', 'yesit', 'libtard', 'know', 'your', 'laugh', 'realli', 'media', 'arent', 'pick', 'get', 'togeth', 'would', 'physic', 'threaten', 'boy', 'us', 'complet', 'slander', 'name', 'wasnt', 'im', 'honestli', 'ya', 'cours', 'fuck', 'least', 'own', 'apolog', 'threat', 'way', 'line', 'liar', 'doesnt', 'even'

In [39]:
word2idx = get_word2idx(tokenized_corpus, vocabulary)
print(len(word2idx))

5597


In [40]:
idx2word = get_idx2word(vocabulary)
print(len(idx2word))

5596


In [41]:
sentences_lengths = [len(sentence) for sentence in tokenized_corpus]
max_len = np.max(np.array(sentences_lengths))

train_sentences_tensor, train_labels_tensor = parse_input(tokenized_corpus, word2idx, train_labels, max_len)

print(train_sentences_tensor)
print(train_labels_tensor)

print(train_sentences_tensor.shape)
print(train_labels_tensor.shape)

tensor([[   1,    1,    1,  ...,    0,    0,    0],
        [   1,   23,   24,  ...,    0,    0,    0],
        [   1,   27,   28,  ...,    0,    0,    0],
        ...,
        [   1,    1,    1,  ...,    0,    0,    0],
        [   1, 1618,  245,  ...,    0,    0,    0],
        [   1,    1,    1,  ...,    0,    0,    0]])
tensor([1., 0., 0.,  ..., 2., 2., 2.])
torch.Size([2480, 81])
torch.Size([2480])


In [42]:
test_file = 'validation.tsv'
test_corpus, test_labels = parse_dataset_task_c(test_file)

inds = len([0 for l in test_labels if l == 0])
groups = len([1 for l in test_labels if l == 1])
oths = len([2 for l in test_labels if l == 2])

print("Individual " + str(inds))
print("Offensives " + str(groups))
print("Others " + str(oths))
  
print(test_corpus)
print(test_labels)

print(len(test_corpus))
print(len(test_labels))

Individual 30
Offensives 4
Others 5
['hughhewitt mishacollins what the hell what does that tweet have to do with gun control maybe try to make your tweet have some sort of sense', 'guess ima have to beat some lil kids asses today cause lil becky not about to but my kid and get away with it ', 'breitbartnews little marco trump will get things done', 'realdonaldtrump everyone already know what you are trying to do with the fake news and witch hunt shit umits not working', 'if its not about me its about matt blah blah blah worrrry about your bf who makes you feel like shit but you act like yall good ', 'saeychung oh she is the worst ugh', 'breitbartnews obama fed the country shit sandwiches for 8 years maybe jim just has his addled mind confused about dates and who fed who what ', 'breitbartnews ironic because shes just like a shotguntwo cocks and shes ready to blow', 'hot usa latina girlfriend sucking so nicely 5 min ', 'realjack what you never see is us conservatives beating up on the m

In [0]:
def parse_in(tokenized_corpus, word2idx, labels, max_len):
    # we index our sentences
    vectorized_sentences = [[word2idx[token] for token in sentence if token in word2idx] for sentence in tokenized_corpus]
  
  
    # we create a tensor of a fixed size filled with zeroes for padding
    sentences_tensor = Variable(torch.zeros((len(vectorized_sentences), max_len))).long()
    sentences_lengths = [len(sentence) for sentence in vectorized_sentences]

    # we fill it with our vectorized sentences 
    for idx, (sentence, sentence_len) in enumerate(zip(vectorized_sentences, sentences_lengths)):
        sentences_tensor[idx, :sentence_len] = torch.LongTensor(sentence)
            
    labels_tensor = torch.FloatTensor(labels)

    return sentences_tensor, labels_tensor

In [44]:
tokenized_valid_corpus = tokenize_f(valid_corpus)

print(len(tokenized_valid_corpus))
print(len(valid_corpus))
print(len(valid_labels))

valid_sentences_tensor, valid_labels_tensor = parse_in(tokenized_valid_corpus, word2idx, valid_labels, max_len)

print(valid_sentences_tensor)
print(valid_labels_tensor)

print(max_len)

print(valid_sentences_tensor.shape)
print(valid_labels_tensor.shape)

797
797
797
tensor([[   1,   21,   58,  ...,    0,    0,    0],
        [   1,    1,  161,  ...,    0,    0,    0],
        [1295, 1858,   61,  ...,    0,    0,    0],
        ...,
        [   1,  547,  115,  ...,    0,    0,    0],
        [   1,    1,   51,  ...,    0,    0,    0],
        [1556,  935,  355,  ...,    0,    0,    0]])
tensor([0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 2., 0., 2., 2., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 1., 1., 2., 0., 1., 0., 2., 1.,
        1., 2., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 2.,
        1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 2., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 2., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 2., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 2., 2., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 2., 1., 0.

In [45]:
tokenized_test_corpus = tokenize_f(test_corpus)
test_sentences_tensor, test_labels_tensor = parse_input(tokenized_test_corpus, word2idx, test_labels, max_len)

print(test_sentences_tensor)
print(test_labels_tensor)

print(test_sentences_tensor.shape)
print(test_labels_tensor.shape)

tensor([[ 674,   75,  117,  ...,    0,    0,    0],
        [ 302, 2258, 1588,  ...,    0,    0,    0],
        [1629,  199,   86,  ...,    0,    0,    0],
        ...,
        [ 604,  782, 1842,  ...,    0,    0,    0],
        [ 101,    0,    0,  ...,    0,    0,    0],
        [1095,   58, 1079,  ...,    0,    0,    0]])
tensor([0., 0., 0., 0., 0., 0., 1., 0., 2., 2., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 2., 0., 0., 1., 0., 0., 2., 0., 0., 0., 0.,
        0., 0., 2.])
torch.Size([39, 81])
torch.Size([39])


In [0]:
def train_model_custom(model, optimizer, loss_fn, feature_train, target_train, feature_valid, target_valid, feature_test, target_test):
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        predictions = model(feature_train)
        loss = loss_fn(predictions, target_train.type(torch.LongTensor))
        acc = accuracy_task_c(predictions, target_train.type(torch.LongTensor))
        loss.backward()
        optimizer.step()

        epoch_loss = loss.item()
        epoch_acc = acc
  
        model.eval()
  
        with torch.no_grad():

            predictions_valid = model(feature_valid)
            loss = loss_fn(predictions_valid, target_valid.type(torch.LongTensor))
            acc = accuracy_task_c(predictions_valid, target_valid.type(torch.LongTensor))
            valid_loss = loss.item()
            valid_acc = acc

        print(f'| Epoch: {epoch:02} | Train Loss: {epoch_loss:.3f} | Train Acc: {epoch_acc*100:.2f}% | Val. Loss: {valid_loss:.3f} | Val. Acc: {valid_acc*100:.2f}% |')
    
    model.eval()

    with torch.no_grad():
 
        predictions = model(feature_test)
        loss = loss_fn(predictions, torch.tensor(target_test).type(torch.LongTensor))
        acc = accuracy_task_c(predictions, torch.tensor(target_test).type(torch.LongTensor))
        print(f'| Test Loss: {loss:.3f} | Test Acc: {acc*100:.2f}%')
        f_measure_task_c(predictions, target_test)

    print(np.count_nonzero(target_test))

In [47]:
epochs=100

INPUT_DIM = len(word2idx)
EMBEDDING_DIM = 100
OUTPUT_DIM = 3
LEARNING_RATE = 0.0008

# the hyperparamerts specific to CNN
# we define the number of filters
N_OUT_CHANNELS = 100
# we define the window size
WINDOW_SIZE = 2
# we apply the dropout with the probability 0.5
DROPOUT = 0.5

model = CNN(INPUT_DIM, EMBEDDING_DIM, N_OUT_CHANNELS, WINDOW_SIZE, OUTPUT_DIM, DROPOUT)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
# loss_fn = nn.BCEWithLogitsLoss()
loss_fn = torch.nn.CrossEntropyLoss()

train_model_custom(model, optimizer, loss_fn, train_sentences_tensor, train_labels_tensor, valid_sentences_tensor, valid_labels_tensor, test_sentences_tensor, test_labels)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:64: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


| Epoch: 00 | Train Loss: 1.400 | Train Acc: 26.13% | Val. Loss: 1.236 | Val. Acc: 17.94% |
| Epoch: 01 | Train Loss: 1.300 | Train Acc: 28.79% | Val. Loss: 1.127 | Val. Acc: 33.38% |
| Epoch: 02 | Train Loss: 1.207 | Train Acc: 35.32% | Val. Loss: 1.047 | Val. Acc: 49.18% |
| Epoch: 03 | Train Loss: 1.138 | Train Acc: 40.65% | Val. Loss: 0.994 | Val. Acc: 54.71% |
| Epoch: 04 | Train Loss: 1.083 | Train Acc: 46.77% | Val. Loss: 0.963 | Val. Acc: 55.83% |
| Epoch: 05 | Train Loss: 1.073 | Train Acc: 47.78% | Val. Loss: 0.950 | Val. Acc: 55.83% |
| Epoch: 06 | Train Loss: 1.065 | Train Acc: 50.56% | Val. Loss: 0.946 | Val. Acc: 55.83% |
| Epoch: 07 | Train Loss: 1.051 | Train Acc: 52.78% | Val. Loss: 0.945 | Val. Acc: 55.83% |
| Epoch: 08 | Train Loss: 1.064 | Train Acc: 53.06% | Val. Loss: 0.944 | Val. Acc: 55.83% |
| Epoch: 09 | Train Loss: 1.049 | Train Acc: 53.23% | Val. Loss: 0.942 | Val. Acc: 56.09% |
| Epoch: 10 | Train Loss: 1.057 | Train Acc: 52.18% | Val. Loss: 0.938 | Val. Ac

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:76: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


In [0]:
testing = read_csv('test_set_taskc.tsv')

tweets = [row['tweet'] for row in testing]
tokenized_corpus = tokenize_f(tweets)

test_tensor, labels_tensor = parse_input(tokenized_corpus, word2idx, test_labels, max_len)

In [49]:
predictions_test = model(test_tensor).squeeze(1)

output = torch.nn.functional.log_softmax(predictions_test).max(dim = 1)[1]

print(output)

print(len(output))

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
213


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
ids = [row['id'] for row in testing]
out = []
for e in output.detach().numpy():
    if e == 0:
        out.append("IND")
    elif e == 1:
        out.append("GRP")
    else:
        out.append("OTH")
   
  
zipped = list(zip(ids, out))

with open('predictions_task_c_split_stemming_augment_window_2.csv', "w") as f:
    writer = csv.writer(f, dialect='excel')
    for row in zipped:
        writer.writerow(row)